source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '5.1.3'

gem 'activesupport', '~> 5.1', '>= 5.1.3'
gem 'bootstrap-sass', '3.3.7'
gem 'coffee-rails', '4.2.2'
gem 'elasticsearch-model', '5.0.1'
gem 'elasticsearch-rails', '5.0.1'
gem 'erubis', '2.7'
gem 'jbuilder', '2.7.0'
gem 'mysql2', '>= 0.3.18', '< 0.5'
gem 'puma', '3.7'
gem 'rails_stdout_logging', '0.0.5'
gem 'sass-rails', '5.0.6'
gem 'turbolinks', '5'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'uglifier', '1.3.0'

group :development do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'rubocop', require: false
  gem 'faker', '1.4.3'
end

group :test do
  gem 'capybara', '2.13.0'
  gem 'spring'
  gem 'spring-watcher-listen', '2.0.0'
  gem 'web-console', '3.3.0'
end
