version: '2'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

services:
  prometheus:
#    image: prom/prometheus:v1.6.1
    image: ajeetraina/prometheus-armv7
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    depends_on:
      - cadvisor
    networks:
      - back-tier

  node-exporter:
    container_name: node-exporter
#    image: prom/node-exporter:v0.14.0
    image: zeiot/rpi-node_exporter:0.13.0
    restart: always
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
      - ./node-exporter/collector:/home/collector
    command:
      - '-collector.procfs=/host/proc'
      - '-collector.sysfs=/host/sysfs'
      - '-collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
      - '--collector.textfile.directory=/home/collector'
      - '--collectors.enabled=conntrack,diskstats,entropy,filefd,filesystem,loadavg,mdadm,meminfo,netdev,netstat,stat,textfile,time,vmstat'
    expose:
      - 9100
    networks:
      - back-tier

  alertmanager:
    container_name: alertmanager
#    image: prom/alertmanager:v0.6.1
    image: zeiot/rpi-alertmanager:0.6.1
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - back-tier
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'

  cadvisor:
    container_name: cadvisor
#    image: google/cadvisor:v0.25.0
    image: solidnerd/rpi-cadvisor:0.25.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
    networks:
      - back-tier

  grafana:
    container_name: grafana
#    image: grafana/grafana:4.2.0
    image: fg2it/grafana-armhf:v4.2.0
    environment:
      GF_SECURITY_ADMIN_USER: admin-user
      GF_SECURITY_ADMIN_PASSWORD: admin-pass
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_USERS_ALLOW_ORG_CREATE: "false"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - back-tier

  nginx:
    container_name: nginx
    image: armhfbuild/nginx:1
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      # - ./_log/nginx:/var/log/nginx
    ports:
      - 13000:80
    links:
      - grafana
    networks:
      - back-tier
      - front-tier
