version: '2'
services:

  nginx:
    image: nginx:1.11.13-alpine
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./_log/nginx:/var/log/nginx
    ports:
      - 80:80
    links:
      - fluentd

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./_log/nginx:/var/log/nginx
    links:
      - elasticsearch
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:5.3.0-alpine
    ports:
      - 9200:9200

  kibana:
    image: kibana:5.3.0
    links:
      - "elasticsearch"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
